---
title: "BIO593_Assignment3"
author: "Kevin Wong, Danielle Jordan, Roxy Roja"
date: '2018-03-26'
output: html_document
---

```{r Intro, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction of the data

This document uses data with life-history, population, and ecological examples. This data can be cited here: http://dx.doi.org/10.6084/m9.figshare.1314459. We will provide an indepth analysis containing plots that visually represent trends in the data and statistical analyses to accurately describe the trends. 

## Loading Data and Installing packages
```{r load data, echo=TRUE, cache=FALSE, results=FALSE, message=FALSE, warning=FALSE}
#download.file("https://ndownloader.figshare.com/files/2292169" , "BIO593_Assignment3/data/portal_data_joined.csv") 
#download.file("https://ndownloader.figshare.com/files/2292171" , "data/portal_data.sqlite", mode = "wb")
#surveys <- read.csv("BIO593_Assignment3/data/portal_data_joined.csv") #uploading csv
```

```{r install packages, echo=TRUE, results=FALSE, message=FALSE, warning=FALSE}
#install.packages(c("dbplyr","RSQLite","tidyverse"))
library(dbplyr)
library(RSQLite)
library(tidyverse)
```

